parameters:
  - name: BuildType
    displayName: 'Select your build type'
    default: debug
    values:
      - debug
      - staging
      - release

  - name: OS
    displayName: Operating System
    type: string
    default: windows-latest
    values:
      - windows-latest
      - vs2017-win2016
      - ubuntu-latest
      - ubuntu-16.04
      - macOS-latest
      - macOS-10.14

trigger:
  - main


stages:
  - stage: 
    displayName: 'Android ${{ parameters.BuildType }} build'
    jobs:
      - job: 
        workspace:
          clean: all      
        pool:
          vmImage: ${{ parameters.OS }}

        steps:
          - task: Gradle@2
            displayName: 'Building Project'
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              publishJUnitResults: false
              testRunTitle: 'InvestorCentreAndroidTest'
              testResultsFiles: '**/TEST-*.xml'
              tasks: assemble${{ parameters.BuildType }}
              codeCoverageToolOption: 'None'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: 'default'
              jdkArchitectureOption: 'x64'
              checkStyleRunAnalysis: false
              findBugsRunAnalysis: false

